In [1]:
#Data Types
I = 5
print(I+1)
type(I)

6


int

In [3]:
I = 5.9
print(I+1)
type(I)

6.9


float

In [5]:
first_name = "Manas"
second_name = " Utthasini"
print(first_name+second_name)
type(first_name)

Manas Utthasini


str

In [7]:
#containers
#data structures
#Lists
fruits = ['apple', 'orange', 'banana','peach']
fruits
g = [1,1.2,'manas']


print(fruits[0])
print(fruits[-1])
print(fruits[2:4])


apple
peach
['banana', 'peach']


In [9]:
#create a list of numbers from  1 to n using the function 'range'
list(range(10,100))

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [11]:
#Tuples  sequence of values which can't modified
mycity = ('kolkata','darjeeling',2)
print(mycity)

('kolkata', 'darjeeling', 2)


In [13]:
mycity(1) = 'howrah'

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (3952633725.py, line 1)

In [15]:
#Disctionaries
car = {'name' : ['marcedes benz', 'BMW'], 'model' : 432, 'color' : 'Blue'}

In [17]:
print(car['name'])
print(car['model'])

['marcedes benz', 'BMW']
432


In [19]:
#Boolean
print(10>5 and 5>6)
print(10>5 or 5>6)

False
True


In [25]:
#Conditional statements
a = int(input('enter first number :'))
b = int(input('enter second number :'))

enter first number : 7
enter second number : 8


In [63]:
if a>b:
    print(a, 'is greater than',b)
elif a==b:
    print(a,'is equal to',b)
else:
    print(a, 'is less than',b)


5 is equal to 5


In [73]:
#loops
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [1]:
#while loop
i=1
while i<11:
    print(i)
    i = i+1

1
2
3
4
5
6
7
8
9
10


In [7]:
#loops using break and continue
print('+++++++++++++++loop using break++++++++++++++++')
for i in range(1,11):
    if i%3 == 0:
      break
    else:
        print(i)
print('+++++++++++++++loop using continue++++++++++++++++')
for i in range(1,11):
    if i%3 == 0:
      continue
    else:
        print(i)

+++++++++++++++loop using break++++++++++++++++
1
2
+++++++++++++++loop using continue++++++++++++++++
1
2
4
5
7
8
10


In [9]:
#functions
def add(a,b):
    return a+b
a = int(input('enter a : '))
b = int(input('enter b : '))
add(a,b)

enter a :  5
enter b :  8


13

In [15]:
def man_range(start,stop,step):
    mylist = []
    while start<stop:
        mylist.append(start)
        start+=step
    return mylist

In [19]:
print(man_range(10,20,2))

[10, 12, 14, 16, 18]


In [21]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [23]:
#Vector operations in python
#Importing module into environment
import numpy as np

In [25]:
arr = np.array([10,20,30,40,50,60,70,80])

In [27]:
#to check dimentionb of array
arr.shape

(8,)

In [29]:
#can query in arrays for example..........
arr[arr>50]

array([60, 70, 80])

In [37]:
#arrithmatic operations
a= np.arange(12)
b= np.arange(10,22)

In [39]:
print(a,b)

[ 0  1  2  3  4  5  6  7  8  9 10 11] [10 11 12 13 14 15 16 17 18 19 20 21]


In [41]:
print(np.add(a,b))

[10 12 14 16 18 20 22 24 26 28 30 32]


In [43]:
print(np.subtract(a,b))

[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]


In [45]:
print(np.multiply(a,b))

[  0  11  24  39  56  75  96 119 144 171 200 231]


In [47]:
print(np.divide(a,b))

[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421 0.5        0.52380952]


In [49]:
np.add(a,b)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [55]:
#multidimentional arrays
m = np.array([[13,24,35],[435,34,43],[33,44,321]])
m

array([[ 13,  24,  35],
       [435,  34,  43],
       [ 33,  44, 321]])

In [59]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
#let us try out basic arrithmatic operations
np.add(a,m)

array([[ 13,  25,  37],
       [438,  38,  48],
       [ 39,  51, 329]])

In [65]:
np.subtract(a,m)

array([[ -13,  -23,  -33],
       [-432,  -30,  -38],
       [ -27,  -37, -313]])

In [67]:
np.multiply(a,m)

array([[   0,   24,   70],
       [1305,  136,  215],
       [ 198,  308, 2568]])

In [71]:
np.divide(a,m)

array([[0.        , 0.04166667, 0.05714286],
       [0.00689655, 0.11764706, 0.11627907],
       [0.18181818, 0.15909091, 0.02492212]])

In [73]:
#calculate inverse of a matrix
np.linalg.inv(m)

array([[-3.51150600e-03,  2.39912691e-03,  6.14961148e-05],
       [ 5.37958671e-02, -1.17465364e-03, -5.70824064e-03],
       [-7.01289239e-03, -8.56275017e-05,  3.89138074e-03]])